### ISSUE TITLE
sparse ores are generating within quark basalt ''veins'' in nether

### ISSUE THREAD

**Issue by DoomSquirter** [Beyond-Reality/Beyond-Realty-Farscapes#35]
topic.  basalt generating naturally in nether but within the basalt is overworld textured sparse ores of various types.  Bug or intentional?

**Comment by Dominance** [comment]
What is basalts ore dictionary?


On Jun 24, 2017 11:49 AM, "DoomSquirter" <notifications@github.com> wrote:

topic. basalt generating naturally in nether but within the basalt is
overworld textured sparse ores of various types. Bug or intentional?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Beyond-Reality/Beyond-Realty-Farscapes/issues/35>, or mute
the thread

**Comment by leagris** [comment]
> What is basalts ore dictionary?

`stoneBasalt`
